// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using db;

#nullable disable

namespace DB_Side.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("db.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Duration = 30,
                            InstructorId = 1,
                            Name = "Programming 1"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Duration = 40,
                            InstructorId = 4,
                            Name = "Data Structures"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            Duration = 35,
                            InstructorId = 2,
                            Name = "Database"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 3,
                            Duration = 25,
                            InstructorId = 3,
                            Name = "Software Testing"
                        });
                });

            modelBuilder.Entity("db.CourseSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.ToTable("CourseSessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 1,
                            Title = "Intro to Programming"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            Date = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 4,
                            Title = "Linked Lists"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            Date = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 2,
                            Title = "SQL Basics"
                        });
                });

            modelBuilder.Entity("db.CourseSessionAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseSessionId")
                        .HasColumnType("int");

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseSessionId");

                    b.HasIndex("StudentId");

                    b.ToTable("CourseSessionAttendances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseSessionId = 1,
                            Grade = 90,
                            Notes = "Excellent",
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseSessionId = 1,
                            Grade = 80,
                            Notes = "Good",
                            StudentId = 2
                        },
                        new
                        {
                            Id = 3,
                            CourseSessionId = 2,
                            Grade = 85,
                            Notes = "Very Good",
                            StudentId = 3
                        },
                        new
                        {
                            Id = 4,
                            CourseSessionId = 3,
                            Grade = 70,
                            Notes = "Needs improvement",
                            StudentId = 4
                        });
                });

            modelBuilder.Entity("db.CourseStudent", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("CourseStudents");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            CourseId = 1,
                            StudentId = 2
                        },
                        new
                        {
                            CourseId = 2,
                            StudentId = 3
                        },
                        new
                        {
                            CourseId = 3,
                            StudentId = 4
                        },
                        new
                        {
                            CourseId = 4,
                            StudentId = 5
                        });
                });

            modelBuilder.Entity("db.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId")
                        .IsUnique()
                        .HasFilter("[ManagerId] IS NOT NULL");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Building A",
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Building B",
                            Name = "Information Systems"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Building C",
                            Name = "Software Engineering"
                        });
                });

            modelBuilder.Entity("db.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            FirstName = "Ahmed",
                            LastName = "Ali",
                            Phone = "010111111"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            FirstName = "Sara",
                            LastName = "Mohamed",
                            Phone = "010222222"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            FirstName = "Omar",
                            LastName = "Hassan",
                            Phone = "010333333"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 1,
                            FirstName = "Mona",
                            LastName = "Adel",
                            Phone = "010444444"
                        });
                });

            modelBuilder.Entity("db.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Ali",
                            LastName = "Mahmoud",
                            Phone = "011111111"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Nour",
                            LastName = "Samy",
                            Phone = "011222222"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Youssef",
                            LastName = "Khaled",
                            Phone = "011333333"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Huda",
                            LastName = "Adel",
                            Phone = "011444444"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Karim",
                            LastName = "Fathy",
                            Phone = "011555555"
                        });
                });

            modelBuilder.Entity("db.Course", b =>
                {
                    b.HasOne("db.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("db.Instructor", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("db.CourseSession", b =>
                {
                    b.HasOne("db.Course", "Course")
                        .WithMany("Sessions")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("db.Instructor", "Instructor")
                        .WithMany("CourseSessions")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("db.CourseSessionAttendance", b =>
                {
                    b.HasOne("db.CourseSession", "CourseSession")
                        .WithMany("Attendances")
                        .HasForeignKey("CourseSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("db.Student", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseSession");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("db.CourseStudent", b =>
                {
                    b.HasOne("db.Course", "Course")
                        .WithMany("CourseStudents")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("db.Student", "Student")
                        .WithMany("CourseStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("db.Department", b =>
                {
                    b.HasOne("db.Instructor", "Manager")
                        .WithOne("ManagedDepartment")
                        .HasForeignKey("db.Department", "ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("db.Instructor", b =>
                {
                    b.HasOne("db.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("db.Course", b =>
                {
                    b.Navigation("CourseStudents");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("db.CourseSession", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("db.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("db.Instructor", b =>
                {
                    b.Navigation("CourseSessions");

                    b.Navigation("Courses");

                    b.Navigation("ManagedDepartment")
                        .IsRequired();
                });

            modelBuilder.Entity("db.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("CourseStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
